complexity:
  LongMethod:
    threshold: 150
  ComplexMethod:
    threshold: 20
  LongParameterList:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated: [ 'AllowMagicNumber' ]
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false

naming:
  TopLevelPropertyNaming:
    # 한글변수도 가능하도록 함
    # See : https://github.com/sungbinland/duckie-quack-quack/pull/82#discussion_r962213545
    constantPattern: '[A-Z가-힣][A-Za-z0-9가-힣_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false
  VariableNaming:
    active: false
