complexity:
  LongMethod:
    threshold: 100
  LongParameterList:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated: [ 'AllowMagicNumber' ]
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false
  VariableNaming:
    active: false
