[versions]
# plugins
dokka = "1.7.10"
ktlint-gradle = "10.3.0"
# https://github.com/JLLeitschuh/ktlint-gradle/issues/589
# klint 최신 버전과 사용 불가
ktlint-source = "0.45.2"
detekt = "1.21.0"

# build
gradle = "7.4.0-alpha09"
kotlin = "1.7.10"

# compose
compose-core = "1.2.1"
compose-compiler = "1.3.0"
compose-activity = "1.5.1"
compose-lifecycle-vm = "2.4.1"
compose-constraintlayout = "1.0.1"
landscapist = "1.6.1"
accompanist = "0.26.1-alpha"

# tools
jacoco = "0.8.8"
lint = "30.2.2"
logeukes = "1.0.0"
profileinstaller = "1.2.0"
customview-poolingcontainer = "1.0.0"

# androidx
androidx-junit = "1.1.3"
androidx-benchmark = "1.1.0"

# test
junit = "4.13.2"
junit-engine = "5.9.0"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }

[libraries]
build-dokka = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-core" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-core" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapist" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-core" } # debugImplementation
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-core" }

customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" } # debugImplementation

lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" } # compileOnly

util-logeukes = { module = "land.sungbin:logeukes", version.ref = "logeukes" }
util-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-benchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }

test-lint = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
test-junit-core = { module = "junit:junit", version.ref = "junit" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-engine" } # testRuntimeOnly
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-core" } # debugImplementation
test-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-core" } # androidTestImplementation

[bundles]
test-lint = ["lint-core", "test-lint"]
compose-core = ["compose-foundation", "compose-activity", "compose-tooling-preview"]
compose-debug = ["compose-tooling", "customview-poolingcontainer"] # debugImplementation
benchmark = ["androidx-junit", "androidx-benchmark"]
