[versions]
# plugins
dokka = "1.6.10"
ktlint = "10.2.1"
detekt = "1.20.0-RC1"

# build
gradle = "7.4.0-alpha09"
kotlin = "1.7.10"

# compose
compose-core = "1.3.0-alpha03"
compose-compiler = "1.3.0"
compose-activity = "1.5.1"
compose-lifecycle-vm = "2.4.1"
landscapist = "1.6.1"
accompanist = "0.26.1-alpha"

# tools
logeukes = "1.0.0"
profileinstaller = "1.2.0"
customview = "1.2.0-alpha01"
customview-poolingcontainer = "1.0.0"

# test
junit = "4.13.2"
junit-engine = "5.9.0"

# lints
# TODO

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[libraries]
build-dokka = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

compose-fondation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-core" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapist" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-core" } # debugImplementation
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-core" }

customview-core = { module = "androidx.customview:customview", version.ref = "customview" } # debugImplementation
customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" } # debugImplementation

util-logeukes = { module = "land.sungbin:logeukes", version.ref = "logeukes" }
util-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

test-junit-core = { module = "junit:junit", version.ref = "junit" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-engine" } # testRuntimeOnly
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-core" } # debugImplementation
test-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-core" } # androidTestImplementation

[bundles]
compose-core = ["compose-fondation", "compose-activity", "compose-glide", "compose-tooling-preview"]
compose-debug = ["compose-tooling"]
customview = ["customview-core", "customview-poolingcontainer"]
