[versions]
# plugins
dokka = "1.7.10"
ktlint-gradle = "11.0.0"
# https://github.com/JLLeitschuh/ktlint-gradle/issues/589
# klint 최신 버전과 사용 불가
ktlint-source = "0.45.2"
detekt = "1.21.0"
paparazzi = "1.0.0"
ksp = "1.7.10-1.0.6"
gradle-maven-publish = "0.22.0"

# build
gradle = "7.4.0-alpha10"
kotlin-core = "1.7.10"
kotlin-metadata = "0.5.0"

# compose
compose-core = "1.2.1"
compose-compiler = "1.3.0"
compose-material3 = "1.0.0-beta02"
compose-activity = "1.5.1"
compose-lifecycle-vm = "2.4.1"
compose-constraintlayout = "1.0.1"
landscapist = "1.6.1"
accompanist = "0.26.1-alpha"

# tools
kover = "0.6.0"
lint = "30.3.0"
logeukes = "1.0.0"
ktx-core = "1.9.0"
systemuicontroller = "1.0.1"
profileinstaller = "1.2.0"
customview-poolingcontainer = "1.0.0"
kotlin-collections-immutable = "0.3.5"

# androidx
androidx-datastore = "1.0.0"
androidx-junit = "1.1.3"
androidx-benchmark = "1.1.0"

# test
junit = "4.13.2"
junit-engine = "5.9.0"
test-parameter-injector = "1.8"

# quack
quack-bom = "1.0.0-dev06"
quack-ui-components = "1.0.0-dev07"
quack-lint-core = "1.0.0-dev07"
quack-lint-quack = "1.0.0-dev07"
quack-lint-compose = "1.0.0-dev07"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }
gradle-maven-publish-base = { id = "com.vanniktech.maven.publish.base", version.ref = "gradle-maven-publish" }

[libraries]
build-dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
build-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
build-kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
build-gradle-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-maven-publish" }

ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-core" }
kotlin-metadata = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlin-metadata" }
kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }

quack-ui-components = { module = "team.duckie.quack:quack-ui-components", version.ref = "quack-ui-components" }
quack-lint-core = { module = "team.duckie.quack:quack-lint-core", version.ref = "quack-lint-core" }
quack-lint-quack = { module = "team.duckie.quack:quack-lint-quack", version.ref = "quack-lint-quack" }
quack-lint-compose = { module = "team.duckie.quack:quack-lint-compose", version.ref = "quack-lint-compose" }

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-core" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-core" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintlayout" }
compose-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapist" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-core" } # debugImplementation
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-core" }

customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" } # debugImplementation

lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" } # compileOnly

ktx-core = { module = "androidx.core:core-ktx", version.ref = "ktx-core" }

util-logeukes = { module = "land.sungbin:logeukes", version.ref = "logeukes" }
util-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
util-systemuicontroller = { module = "land.sungbin:systemuicontroller", version.ref = "systemuicontroller" }

androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-benchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }

test-parameter-injector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-parameter-injector" }
test-lint = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
test-junit-core = { module = "junit:junit", version.ref = "junit" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-engine" } # testRuntimeOnly
test-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-core" } # debugImplementation
test-compose-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-core" } # androidTestImplementation

[bundles]
test-lint = ["lint-core", "test-lint"]
compose-core = ["compose-foundation", "compose-activity", "compose-tooling-preview"]
compose-debug = ["compose-tooling", "customview-poolingcontainer"] # debugImplementation
benchmark = ["androidx-junit", "androidx-benchmark"]
