[versions]
gradle-android = "8.0.0-beta02"
gradle-publish-maven = "0.24.0"

kotlin-core = "1.8.0"
kotlin-dokka = "1.7.20"
kotlin-detekt = "1.22.0"
kotlin-ktlint-gradle = "11.1.0"
# https://github.com/JLLeitschuh/ktlint-gradle/issues/627
# 최신 버전의 ktlint와 editorconfig가 호환되지 않음
kotlin-ktlint-source = "0.45.2"
kotlin-collections-immutable = "0.3.5"

androidx-core-ktx = "1.9.0"
androidx-datastore = "1.0.0" # for Playground
androidx-benchmark = "1.1.1"
androidx-profileinstaller = "1.2.2"

compose-uiutil = "1.3.3"
compose-compiler = "1.4.0"
compose-material = "1.3.1"
compose-animation = "1.3.3"
compose-material3 = "1.0.1" # for Playground
compose-activity = "1.6.1"
compose-coil = "2.2.2"

test-junit-core = "4.13.2"
test-junit-engine = "5.9.2"
test-junit-compose = "1.3.3"
test-strikt = "0.34.1"
test-paparazzi = "1.2.0"
test-injector-parameter = "1.10"

[plugins]
gradle-publish-maven-core = { id = "com.vanniktech.maven.publish", version.ref = "gradle-publish-maven" }
gradle-publish-maven-base = { id = "com.vanniktech.maven.publish.base", version.ref = "gradle-publish-maven" }

kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlin-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "kotlin-detekt" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }

test-paparazzi = { id = "app.cash.paparazzi", version.ref = "test-paparazzi" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }
gradle-publish-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-publish-maven" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
kotlin-dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "kotlin-dokka" }
kotlin-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin-dokka" }
kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-benchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }

compose-uiutil = { module = "androidx.compose.ui:ui-util", version.ref = "compose-uiutil" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-animation" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "compose-coil" }

test-junit-core = { module = "junit:junit", version.ref = "test-junit-core" }
test-junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-engine" } # testRuntimeOnly
test-junit-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "test-junit-compose" } # androidTestImplementation
test-strikt = { module = "io.strikt:strikt-core", version.ref = "test-strikt" }
test-injector-parameter = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-injector-parameter" }

detekt-plugin-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "kotlin-detekt" }
