name: Android CD
on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  android-deploy:
    if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release') && contains(github.event.pull_request.labels.*.name, 'deploy') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # We should use the "real" build configuration file for app deployments.
      - name: Decrypt secrets.tar.gpg
        run: gpg --quiet --batch --yes --always-trust --decrypt --passphrase="$SECRET_GPG_PASSWORD" --output secrets.tar secrets.tar.gpg
        env:
          SECRET_GPG_PASSWORD: ${{ secrets.SECRET_GPG_PASSWORD }}

      - name: Unzip secrets.tar
        run: tar xvf secrets.tar

      - name: Build apk
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: duckie
          file: playground/build/outputs/apk/release/playground-release.apk
          releaseNotes: |
            마지막 변경 사항 제목: ${{ github.event.pull_request.title }}
            자세한 변경 사항은 https://duckie.team/quack/pr 를 확인해 주세요.
