name: Android CI
on:
  pull_request:
    branches: [ develop ]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decrypt secrets.tar.gpg
        run: gpg --quiet --batch --yes --always-trust --decrypt --passphrase="$SECRET_GPG_PASSWORD" --output secrets.tar secrets.tar.gpg
        env:
          SECRET_GPG_PASSWORD: ${{ secrets.SECRET_GPG_PASSWORD }}

      - name: Unzip secrets.tar
        run: tar xvf secrets.tar

      - name: Run build (includes ktlint/detekt/test check)
        run: ./gradlew build

      - name: Generate merged report by Kover
        if: ${{ contains(github.event.pull_request.labels.*.name, 'test') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew koverMergedReport

      - name: Generate test coverage html report configuration files
        if: ${{ contains(github.event.pull_request.labels.*.name, 'test') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew configurationTestCoverageHtmlReport

      - name: Pushes report html to deploy repository
        if: ${{ contains(github.event.pull_request.labels.*.name, 'test') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "report/test-coverage/"
          destination-github-username: "sungbinland"
          destination-repository-name: "duckie-quack-test-coverage-deploy"
          user-email: ji@sungb.in
          commit-message: |
            #${{ github.event.number }} 에서 생성된 테스트 커버리지

      - name: Generate ui components snapshot
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew recordPaparazziRelease

      - name: Generate snapshots deploy configuration files
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew configurationUiComponentsSnapshotDeploy

      - name: Pushes snapshots to deploy repository
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_UI_DEPLOY_KEY }}
        with:
          source-directory: "ui-components/src/test/snapshots/images/"
          destination-github-username: "sungbinland"
          destination-repository-name: "duckie-quack-ui-components-snapshot-deploy"
          user-email: ji@sungb.in
          commit-message: |
            #${{ github.event.number }} 에서 생성된 스냅샷

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: report/test-coverage/report.xml

      - name: Print all folder tree for debugging
        run: ./gradlew printAllFolderTreeForDebugging

      - name: Print png extension file tree for debugging
        run: ./gradlew printPngExtensionFileTreeForDebugging
