name: Android CI
on:
  pull_request:
    branches: [ develop ]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # A "fake" build configuration file can be used for simple CI works.
      # See: https://github.com/sungbinland/duckie-quack-quack/pull/102#issuecomment-1244937186
      - name: Unzip quackuser-secrets.tar
        run: tar xvf quackuser-secrets.tar

      - name: Run build (includes ktlint/detekt/test check)
        run: ./gradlew build --stacktrace

      - name: Generate merged report by Kover
        if: contains(github.event.pull_request.labels.*.name, 'test')
        run: ./gradlew koverMergedReport --stacktrace

      - name: Upload coverage to Codecov
        if: contains(github.event.pull_request.labels.*.name, 'test')
        uses: codecov/codecov-action@v3
        with:
          files: report/test-coverage/report.xml

      - name: Generate test coverage html report configuration files
        if: ${{ contains(github.event.pull_request.labels.*.name, 'test') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew configurationTestCoverageHtmlReport --stacktrace

      - name: Pushes report html to deploy repository
        if: ${{ contains(github.event.pull_request.labels.*.name, 'test') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_COVERAGE_DEPLOY_KEY }}
        with:
          source-directory: "report/test-coverage"
          destination-github-username: "sungbinland"
          destination-repository-name: "duckie-quack-test-coverage-deploy"
          user-email: ji@sungb.in
          commit-message: |
            #${{ github.event.number }} 에서 생성된 테스트 커버리지

      - name: Generate ui components snapshot
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew recordPaparazziDebug --stacktrace

      - name: Generate snapshots deploy configuration files
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew configurationUiComponentsSnapshotDeploy --stacktrace

      - name: Snapshot files generated by Paparazzi
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: ./gradlew printGenerateSnapshotFiles --stacktrace

      - name: Pushes snapshots to deploy repository
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_UI_DEPLOY_KEY }}
        with:
          source-directory: "ui-components/src/test/snapshots/images"
          destination-github-username: "sungbinland"
          destination-repository-name: "duckie-quack-ui-components-snapshot-deploy"
          user-email: ji@sungb.in
          commit-message: |
            #${{ github.event.number }} 에서 생성된 스냅샷

      - name: Comment test coverage is deployed
        if: ${{ contains(github.event.pull_request.labels.*.name, 'test') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        uses: Code-Hex/neo-cowsay-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cow: 'random'
          cowsay_on_comment: true
          message: |
            새로운 테스트 커버리지 HTML 리포트가 배포되었습니다.
            https://quack-test.duckie.team/ 에서 확인하실 수 있습니다.

      - name: Comment snapshots is deployed
        if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        uses: Code-Hex/neo-cowsay-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cow: 'random'
          cowsay_on_comment: true
          message: |
            새로운 UI 컴포넌트 스냅샷이 배포되었습니다.
            https://quack-ui.duckie.team/ 에서 확인하실 수 있습니다.
