name: Android CI

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

on:
  pull_request:
    paths-ignore: [ '**/**.md', 'website/**' ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-build:
    runs-on: macos-latest
    
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-write-only: ${{ contains(github.event.pull_request.labels.*.name, 'gradle') }}
          cache-read-only: ${{ !contains(github.event.pull_request.labels.*.name, 'gradle') }}

      - name: Code style checks
        run: ./gradlew ktlintCheck detekt

      - name: Run test
        run: ./gradlew test --stacktrace

      - name: Verify components snapshot
        run: ./gradlew :ui:verifyRoborazziDebug

      - name: Run ui test on ui module via gmd
        if: contains(github.event.pull_request.labels.*.name, 'ui')
        run: ./gradlew :ui:pixel4api30aospatdDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Run ui test on casa-ui module via gmd
        if: contains(github.event.pull_request.labels.*.name, 'casa-ui')
        run: ./gradlew :casa-ui:pixel4api30aospatdDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Run build
        run: ./gradlew buildDebug --stacktrace
