name: Android CI
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"
on:
  pull_request:
    branches: [ master ]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Unarchive keystore signing files
        run: |
          gpg --quiet --batch --yes --always-trust --decrypt --passphrase=${{ secrets.SECRET_GPG_PASSWORD }} --output secrets.tar secrets.tar.gpg
          tar xvf secrets.tar

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run build (includes ktlint/detekt/test/binary-compatibility check)
        run: ./gradlew build

      - name: Generate merged report by Kover
        run: ./gradlew koverMergedReport

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: report/test-coverage/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Coverage
          update-comment: true

      - name: Generate test coverage badge
        uses: emibcn/badge-action@v1.2.4
        with:
          label: Test Coverage
          status: ${{ steps.kover.outputs.coverage-overall }}%
          color: FFB341
          path: assets/badge/quackquack/coverage.svg

      - name: Push test coverage badge
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.SUNGBINLAND_BOT_TOKEN }}
        with:
          source-directory: assets/badge/quackquack
          destination-github-username: duckie-team
          destination-repository-name: duckie-test
          user-email: sungbinland.project@gmail.com
          user-name: sungbinland-bot
          target-directory: badge/quackquack

      - name: Push test coverage reports
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.SUNGBINLAND_BOT_TOKEN }}
        with:
          source-directory: report/test-coverage/html
          destination-github-username: duckie-team
          destination-repository-name: duckie-test
          user-email: sungbinland.project@gmail.com
          user-name: sungbinland-bot
          target-directory: report/quackquack
