name: Artifact Publish

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  artifacts-publish:
    if: ${{
      github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'publish') &&
      (contains(github.event.pull_request.labels.*.name, 'bump_major') ||
      contains(github.event.pull_request.labels.*.name, 'bump_minor') ||
      contains(github.event.pull_request.labels.*.name, 'bump_patch')
      ) &&
      (contains(github.event.pull_request.labels.*.name, 'target_lint-core') ||
      contains(github.event.pull_request.labels.*.name, 'target_lint-quack') ||
      contains(github.event.pull_request.labels.*.name, 'target_lint-compose') ||
      contains(github.event.pull_request.labels.*.name, 'target_ui-components')
      )
      }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      # A "fake" build configuration file can be used for artifacts publish works.
      # See: https://github.com/sungbinland/duckie-quack-quack/pull/102#issuecomment-1244937186
      - name: Unzip quackuser-secrets.tar
        run: tar xvf quackuser-secrets.tar

      # [bumpVersion --scan-steps-generator.kt]
      # https://gist.github.com/jisungbin/5cac715eb5133d289f2565c26db9b5e9
      - name: Bump artifact version (type_Major, target_LintCore)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_major') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-core')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="LintCore"

      - name: Bump artifact version (type_Major, target_LintQuack)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_major') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-quack')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="LintQuack"

      - name: Bump artifact version (type_Major, target_LintCompose)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_major') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-compose')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="LintCompose"

      - name: Bump artifact version (type_Major, target_UiComponents)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_major') &&
          contains(github.event.pull_request.labels.*.name, 'target_ui-components')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Major" -Ptarget="UiComponents"

      - name: Bump artifact version (type_Minor, target_LintCore)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_minor') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-core')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Minor" -Ptarget="LintCore"

      - name: Bump artifact version (type_Minor, target_LintQuack)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_minor') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-quack')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Minor" -Ptarget="LintQuack"

      - name: Bump artifact version (type_Minor, target_LintCompose)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_minor') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-compose')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Minor" -Ptarget="LintCompose"

      - name: Bump artifact version (type_Minor, target_UiComponents)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_minor') &&
          contains(github.event.pull_request.labels.*.name, 'target_ui-components')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Minor" -Ptarget="UiComponents"

      - name: Bump artifact version (type_Patch, target_LintCore)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_patch') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-core')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Patch" -Ptarget="LintCore"

      - name: Bump artifact version (type_Patch, target_LintQuack)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_patch') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-quack')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Patch" -Ptarget="LintQuack"

      - name: Bump artifact version (type_Patch, target_LintCompose)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_patch') &&
          contains(github.event.pull_request.labels.*.name, 'target_lint-compose')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Patch" -Ptarget="LintCompose"

      - name: Bump artifact version (type_Patch, target_UiComponents)
        if: ${{
          contains(github.event.pull_request.labels.*.name, 'bump_patch') &&
          contains(github.event.pull_request.labels.*.name, 'target_ui-components')
          }}
        run: ./gradlew bumpVersion --scan -Ptype="Patch" -Ptarget="UiComponents"

      # [publish-steps-generator.kt]
      # https://gist.github.com/jisungbin/ef87cc3d96a40a86689a5bc413cd0763
      - name: Publish lint-core-publish to MavenCentral
        if: contains(github.event.pull_request.labels.*.name, 'target_lint-core')
        run: ./gradlew :lint-core-publish:publish --no-parallel --scan

      - name: Publish lint-quack-publish to MavenCentral
        if: contains(github.event.pull_request.labels.*.name, 'target_lint-quack')
        run: ./gradlew :lint-quack-publish:publish --no-parallel --scan

      - name: Publish lint-compose-publish to MavenCentral
        if: contains(github.event.pull_request.labels.*.name, 'target_lint-compose')
        run: ./gradlew :lint-compose-publish:publish --no-parallel --scan

      - name: Publish ui-components to MavenCentral
        if: contains(github.event.pull_request.labels.*.name, 'target_ui-components')
        run: ./gradlew :ui-components:publish --no-parallel --scan

      - name: Update new versions
        run: |
          git config user.name "sungbinland-bot"
          git config user.email "sungbinland.project@gmail.com"
          git add .
          git commit -m "[CI] bump versions"
          git push
