name: Deploy dokka content
on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  dokka-deploy:
    if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'dokka') && contains(github.event.pull_request.labels.*.name, 'deploy') }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # A "fake" build configuration file can be used for dokka deploy works.
      # See: https://github.com/sungbinland/duckie-quack-quack/pull/102#issuecomment-1244937186
      - name: Unzip quackuser-secrets.tar
        run: tar xvf quackuser-secrets.tar

      - name: Generate dokka content
        run: ./gradlew dokkaHtmlMultiModule --stacktrace

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload dokka artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "documents/dokka"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
