name: Deploy quack ui components snapshot
on:
  pull_request:
    branches: [ develop ]

jobs:
  ui-components-snapshot-deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'UI') && contains(github.event.pull_request.labels.*.name, 'deploy') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decrypt secrets.tar.gpg
        run: gpg --quiet --batch --yes --always-trust --decrypt --passphrase="$SECRET_GPG_PASSWORD" --output secrets.tar secrets.tar.gpg
        env:
          SECRET_GPG_PASSWORD: ${{ secrets.SECRET_GPG_PASSWORD }}

      - name: Unzip secrets.tar
        run: tar xvf secrets.tar

      - name: Run build (includes ktlint/detekt/test check)
        run: ./gradlew build

      - name: Generate ui components snapshot
        run: ./gradlew recordPaparazziRelease

      - name: Generate snapshots deploy configuration files
        run: ./gradlew configurationUiComponentsSnapshotDeploy

      - name: Pushes snapshots to deploy repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_UI_DEPLOY_KEY }}
        with:
          source-directory: "ui-components/src/test/snapshots"
          destination-github-username: "sungbinland"
          destination-repository-name: "duckie-quack-ui-components-snapshot-deploy"
          user-email: ji@sungb.in
          commit-message: |
            #${{ github.event.number }} 에서 생성된 스냅샷
