# https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/ScreenShotTest.yml

# 원래는 Android CI 에 합쳐야 하지만 작업 2개를 동시에 진행하기 위해서 별도 파일로 분리
# 1. build 에서 실패한 경우 / 2. snapshots 검증에서 실패한 경우
# assinger 가 이렇게 2가지 애로 사항을 동시에 처리할 수 있음

name: Verify snapshots
on:
  pull_request:
    branches: [ develop ]

jobs:
  verify-snapshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      # A "fake" build configuration file can be used for simple CI works.
      # See: https://github.com/sungbinland/duckie-quack-quack/pull/102#issuecomment-1244937186
      - name: Unzip quackuser-secrets.tar
        run: tar xvf quackuser-secrets.tar

      - name: Download previous snapshots
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: update-snapshots.yml
          name: snapshots
          path: ui-components-snapshots/src/test/snapshots/images

      - name: Verify snapshots
        continue-on-error: true
        run: ./gradlew :ui-components-snapshots:verifyPaparazziDebug

      - name: Save PR number
        run: |
          mkdir -p ./ui-components-snapshots/out/failures
          echo ${{ github.event.number }} > ./ui-components-snapshots/out/failures/pr_number.txt

      - name: Upload snapshots verify result if verify failed
        if: ${{ hashFiles('ui-components-snapshots/out/failures/*.png') != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: snapshots-verify-result
          path: ui-components-snapshots/out/failures
