name: website-deploy
on:
  push:
  # pull_request:
    # branches: [ 2.x.x ]
    # types: [ closed ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  website-deploy:
    environment:
      name: 'github-pages'
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-latest

    # if: ${{
    #   github.event.pull_request.merged &&
    #   contains(github.event.pull_request.labels.*.name, 'documentation')
    #   }}

    steps:
      - name: Checkout website folder
        uses: Bhacaz/checkout-files@v2
        with:
          files: website

      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Build Docusaurus
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'website/build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
